version: "3.7"
services: 
    db:
        image: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "9000:5432"